version: "3"
services:
  api:
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./:/app
    environment:
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=test
      - DATABASE_NAME=test
      - DATABASE_USERNAME=postgres
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - postgres
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 82:80
    environment:
      PGADMIN_DEFAULT_EMAIL: test@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: admin
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: